import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import predictionsRouter from "./predictions";
import battlesRouter from "./battles";
import analyticsRouter from "./analytics";
import questsRouter from "./quests";
import rewardsRouter from "./rewards";
import withdrawalsRouter from "./withdrawals";
import withdrawalsTonRouter from "./withdrawalsTon";
import creatorWithdrawalsRouter from "./creatorWithdrawals";
import creatorPassRouter from "./creatorPass";
import gemsRouter from "./gems";
import contentSubmitGuardRouter from "./contentSubmitGuard";
import contentStatusGuardRouter from "./contentStatusGuard";
import contentRouter from "./content";
import crashRouter from "./crash";
import marketRouter from "./market";
import activityFeedRouter from "./activityFeed";
import featuresRouter from "./features";
import exchangeRouter from "./exchange";
import tradeCapRouter from "./tradeCap";
import commissionsRouter from "./commissions";
import minesPassPurchaseGuardRouter from "./minesPassPurchaseGuard";
import minesAtomicStartGuardRouter from "./minesAtomicStartGuard";
import minesPassCapRouter from "./minesPassCap";
import minesSafeRevealGuardRouter from "./minesSafeRevealGuard";
import minesRouter from "./mines";

const router: IRouter = Router();
router.use(healthRouter);
router.use(usersRouter);
router.use(predictionsRouter);
router.use(battlesRouter);
router.use(analyticsRouter);
router.use(questsRouter);
router.use(rewardsRouter);
router.use(withdrawalsRouter);
router.use(withdrawalsTonRouter);
router.use(creatorWithdrawalsRouter);
router.use(creatorPassRouter);
router.use(gemsRouter);
router.use(contentSubmitGuardRouter);
router.use(contentStatusGuardRouter);
router.use(contentRouter);
router.use(crashRouter);
router.use(marketRouter);
router.use(activityFeedRouter);
router.use(featuresRouter);
router.use(exchangeRouter);
router.use(tradeCapRouter);
router.use(commissionsRouter);
router.use(minesPassPurchaseGuardRouter);
router.use(minesAtomicStartGuardRouter);
router.use(minesPassCapRouter);
router.use(minesSafeRevealGuardRouter);
router.use(minesRouter);
export default router;
