import { pgTable, text, serial, timestamp, integer, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const usersTable = pgTable("users", {
  id: serial("id").primaryKey(),
  telegramId: text("telegram_id").notNull().unique(),
  username: text("username"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  photoUrl: text("photo_url"),
  tradeCredits: integer("trade_credits").notNull().default(500),
  goldCoins: integer("gold_coins").notNull().default(0),
  creatorCredits: integer("creator_credits").notNull().default(0),
  totalGcEarned: integer("total_gc_earned").notNull().default(0),
  totalCrEarned: integer("total_cr_earned").notNull().default(0),
  totalCrWithdrawn: integer("total_cr_withdrawn").notNull().default(0),
  rankXp: integer("rank_xp").notNull().default(0),
  creatorXp: integer("creator_xp").notNull().default(0),
  valueXp: integer("value_xp").notNull().default(0),
  rankLevel: integer("rank_level").notNull().default(1),
  betaAccessGranted: boolean("beta_access_granted").notNull().default(true),
  betaNumber: integer("beta_number"),
  betaAccessGrantedAt: timestamp("beta_access_granted_at", { withTimezone: true }).notNull().defaultNow(),
  isVip: boolean("is_vip").notNull().default(false),
  vipExpiresAt: timestamp("vip_expires_at", { withTimezone: true }),
  vipPlan: text("vip_plan"),
  vipTrialExpiresAt: timestamp("vip_trial_expires_at", { withTimezone: true }),
  hadVipTrial: boolean("had_vip_trial").notNull().default(false),
  day7BonusClaimed: boolean("day7_bonus_claimed").notNull().default(false),
  gcMilestoneTrialClaimed: boolean("gc_milestone_trial_claimed").notNull().default(false),
  referralVipRewardPending: boolean("referral_vip_reward_pending").notNull().default(false),
  creatorPassPaid: boolean("creator_pass_paid").notNull().default(false),
  creatorPassPaidAt: timestamp("creator_pass_paid_at", { withTimezone: true }),
  hasVerified: boolean("has_verified").notNull().default(false),
  walletAddress: text("wallet_address"),
  referredBy: text("referred_by"),
  loginStreak: integer("login_streak").notNull().default(0),
  lastLoginDate: text("last_login_date"),
  registrationDate: text("registration_date"),
  dailyGcEarned: integer("daily_gc_earned").notNull().default(0),
  dailyGcDate: text("daily_gc_date"),
  dailyBattleGcEarned: integer("daily_battle_gc_earned").notNull().default(0),
  dailyBattleGcDate: text("daily_battle_gc_date"),
  dailyTradeCapBoostGc: integer("daily_trade_cap_boost_gc").notNull().default(0),
  dailyTradeCapBoostDate: text("daily_trade_cap_boost_date"),
  weeklyWithdrawnGc: integer("weekly_withdrawn_gc").notNull().default(0),
  weeklyWithdrawnResetAt: text("weekly_withdrawn_reset_at"),
  dailyGcFromMines: integer("daily_gc_from_mines").notNull().default(0),
  dailyGcFromMinesDate: text("daily_gc_from_mines_date"),
  referralEarnings: integer("referral_earnings").notNull().default(0),
  referralEarningsUnlockedAt: timestamp("referral_earnings_unlocked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertUserSchema = createInsertSchema(usersTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof usersTable.$inferSelect;
